[package]
name = "eliprompt"
version = "0.1.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = "Elegant and informative shell prompt"
license = "MIT"
homepage = "https://github.com/stephaneyfx/eliprompt"
repository = "https://github.com/stephaneyfx/eliprompt.git"
readme = "README.md"
keywords = ["shell", "prompt", "zsh"]

[dependencies]
ansi_term = "0.12.1"
bs58 = "0.3.1"
clap = "2.33.1"
dirs = "3.0.1"
git2 = "0.13.6"
humantime = "2.0.1"
humantime-serde = "1.0.0"
moniclock = "0.1.0"
once_cell = "1.4.0"
palette = "0.5.0"
rgb = "0.8.18"
serde = { version = "1.0.112", features = ["derive"] }
serde_json = "1.0.55"
thiserror = "1.0.20"
